Repository FI18-Trainees/FISocketChat, pull requests merged in 2019-09, with the labels that each got.

#39 fix socket connect url
  src/app/public/js/script.js
Labels: breaking

#42 Global values
  src/app/__init__.py
  src/app/global_values.py
  src/app/sockets.py
Labels: breaking

#47 Update readme.md
  readme.md
Labels: documentation

#50 Feature/errorbox
  src/app/emotes.json
  src/app/public/css/general.css
  src/app/public/js/script.js
  src/app/routes.py
  src/app/templates/index.html
  src/server.py
Labels: enhancement, ux

#65 maybe this fixes issue, due I still can't reproduce error - fixes #61
  src/app/public/js/script.js
Labels: bug, ux

#68 Added auth to socket connection
  .github/workflows/unittest_sockets.yml
  .github/workflows/unittest_sockets_master.yml
  src/app/__init__.py
  src/app/public/js/script.js
  src/app/routes.py
  src/app/sockets.py
  src/app/templates/index.html
  src/server.py
Labels: breaking

#72 Color support
  src/app/public/css/general.css
  src/app/public/js/script.js
  src/app/sockets.py
  tests/test_sockets.py
Labels: breaking, enhancement, ux

#73 added 1 new emote and some clickable emotes
  src/app/emotes.json
  src/app/public/img/wiw.jpg
Labels: ux

#78 Fixes usercount issue
  src/app/global_values.py
  src/app/sockets.py
  src/linux_start_disablelogin.sh
  src/win_start_disablelogin.bat
Labels: bug, ux

#79 remove requirements checkup
  .github/workflows/basic_check.yml
  .github/workflows/basic_check_master.yml
  requirements.txt
  tests/test_requirements.py
  ubuntu_py3.7_patch.sh
  windows_patch.bat
Labels: breaking

#80 Update emotes.json
  src/app/emotes.json
Labels: ux

#81 Refactoring
  src/app/__init__.py
  src/app/emotes.py
  src/app/global_values.py
  src/app/public/js/script.js
  src/app/routes.py
  src/app/shell.py
  src/app/sockets.py
  src/server.py
Labels: enhancement

#82 small design changes, added sitebar and overall applied color scheme
  src/app/public/css/general.css
  src/app/templates/index.html
Labels: enhancement, ux

#83 Emotemenu
  src/app/emotes.json
  src/app/public/css/general.css
  src/app/public/img/nymnCorn.gif
  src/app/public/js/script.js
  src/app/routes.py
  src/app/sockets.py
  src/app/templates/index.html
Labels: breaking, enhancement, ux

#85 using redirect option of login form now
  src/app/__init__.py
Labels: ux
