Repository FI18-Trainees/FISocketChat, pull requests merged in 2019-12, with the labels that each got.

#281 Update script.js
  src/app/public/js/script.js
  src/app/sockets.py
Labels: bug

#291 added approved emote
  src/app/emotes/emotes.json
  src/app/public/img/approved.png
Labels: emotes

#292 added favicon
  src/app/public/favicon.ico
  src/app/routes.py
Labels: feature, ux

#294 fixed method
  src/app/obj/user_manager.py
Labels: bug

#293 changed embed styling for hangman
  src/app/commands/embedtest.py
  src/app/commands/hangman.py
  src/app/emotes/emotes.json
  src/app/obj/embed.py
Labels: ux

#295 moved codeowners to folder it should be in
  .github/CODEOWNERS
Labels: documentation, github

#297 new emotes Pog
  src/app/emotes/emotes.json
  src/app/public/img/stoll3.png
  src/app/public/img/stoll4.png
Labels: emotes

#298 refactored private chathistory
  src/app/__init__.py
  src/app/obj/user_manager.py
  src/app/public/js/script.js
  src/app/routes.py
  src/app/sockets.py
Labels: api, breaking

#299 bug fixes in chathistory
  src/app/routes.py
Labels: api, breaking

#301 added contributors profil pics to readme
  readme.md
Labels: documentation

#303 emotes for tab completion are now alphabetically ordered
  src/app/public/js/script.js
Labels: emotes, ux

#305 monkaS
  src/app/routes.py
  src/app/templates/index.html
  src/config-default/main.json
Labels: breaking, bug, design

#309 added emotes
  src/app/emotes/emotes.json
  src/app/public/img/kappaomega.png
  src/app/public/img/kappaross.png
  src/app/public/img/keepo.png
  src/app/public/img/kekw.gif
  src/app/public/img/oof.gif
  src/app/public/img/pepelaugh.png
  src/app/public/img/tutut.gif
Labels: emotes, ux

#308 some fixes
  src/app/__init__.py
  src/app/sockets.py
  src/app/templates/index.html
Labels: bug, ux

#315 added --cfg-debug param
  src/linux_start_fulldebug.sh
  src/server.py
  src/utils/config.py
  src/win_start_fulldebug.bat
Labels: feature

#316 changed target to es6
  package.json
  tsconfig.json
Labels: breaking

#317 added compile test
  .github/workflows/basic_check.yml
  .github/workflows/basic_check_master.yml
  .github/workflows/tsc_test.yml
  .github/workflows/tsc_test_master.yml
  package.json
  readme.md
Labels: github, unittests

#318 Typescript implementation
  .github/workflows/basic_check.yml
  .github/workflows/basic_check_master.yml
  .github/workflows/tsc_test.yml
  .github/workflows/tsc_test_master.yml
  .gitignore
  package-lock.json
  package.json
  readme.md
  src/app/__init__.py
  src/app/public/js/nanoscroller.js
  src/app/public/js/notify.js
  src/app/public/js/script.js
  src/app/templates/index.html
  src/app/ts/interfaces/IAuthor.ts
  src/app/ts/interfaces/IEmbed.ts
  src/app/ts/interfaces/IFields.ts
  src/app/ts/interfaces/IMedia.ts
  src/app/ts/interfaces/IMessage.ts
  src/app/ts/script.ts
  tsconfig.json
  tslint.json
Labels: breaking, feature

#326 reworked readme for new proj struct
  readme.md
Labels: documentation

#327 refactored pyhton logging
  .github/workflows/pythonlint.yml
  .github/workflows/pythonlint_master.yml
  python/src/app/__init__.py
  python/src/app/commands/__init__.py
  python/src/app/commands/gitversion.py
  python/src/app/emotes/emote_handling.py
  python/src/app/obj/message.py
  python/src/app/obj/system.py
  python/src/app/obj/user_manager.py
  python/src/app/routes.py
  python/src/app/runtime_settings.py
  python/src/app/sockets.py
  python/src/linux_start.sh
  python/src/linux_start_disablelogin.sh
  python/src/linux_start_fulldebug.sh
  python/src/log_config.py
  python/src/server.py
  python/src/utils/__init__.py
  python/src/utils/config.py
  python/src/utils/shell.py
  python/src/win_start_fulldebug.bat
Labels: documentation, feature

#328 fixed path in readme
  readme.md
Labels: documentation

#329 renaming and output rework
  .github/workflows/angular_build_test.yml
  .github/workflows/angular_build_test_master.yml
  python/src/app/commands/__init__.py
  python/src/app/obj/chat_history.py
  python/src/app/routes.py
  readme.md
Labels: documentation, github
