Repository FI18-Trainees/FISocketChat, pull requests merged in 2019-11, with the labels that each got.

#132 fix xd
  src/app/public/js/script.js
Labels: bug

#136 Spam protection
  src/app/public/img/simonW.png
  src/app/public/js/script.js
  src/app/sockets.py
Labels: enhancement

#137 minor changes
  src/app/sockets.py
Labels: bug

#139 command handling
  src/app/__init__.py
  src/app/commands/__init__.py
  src/app/commands/ping.py
  src/app/emotes.py
  src/app/public/img/system.png
  src/app/public/js/script.js
  src/app/routes.py
  src/app/sockets.py
  src/app/user_limiter.py
  src/server.py
  tests/test_sockets.py
Labels: breaking, enhancement, ux

#140 Command/list
  src/app/__init__.py
  src/app/commands/__init__.py
  src/app/commands/list.py
  src/app/global_values.py
  src/app/sockets.py
  src/app/user_limiter.py
Labels: enhancement, ux

#145 Fix assign of ownusername
  src/app/public/js/script.js
Labels: breaking, bug

#144 Regex opt 1
  src/app/__init__.py
  src/app/public/css/general.css
  src/app/routes.py
  src/app/sockets.py
Labels: enhancement

#143 added content to sitebar
  src/app/templates/index.html
Labels: ux

#150 Zaanposni patch 1
  src/app/__init__.py
  src/app/commands/list.py
  src/app/global_values.py
  src/app/sockets.py
Labels: enhancement

#153 /list bugfix and triggered.gif fix
  src/app/commands/list.py
  src/app/emotes.json
Labels: breaking, bug

#154 fixed "Bitte" and "Danke" being stretched and some minor formatting (…
  src/app/emotes.json
Labels: emotes

#155 made sitebar responsive
  src/app/public/css/responsive.css
  src/app/templates/index.html
Labels: ux

#158 Mention on click
  src/app/public/css/general.css
  src/app/public/js/script.js
Labels: enhancement, ux

#161 Create CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#160 added codeblocks, css will be changed later
  src/app/__init__.py
  src/app/public/css/general.css
  src/app/public/js/script.js
  src/app/sockets.py
Labels: enhancement, ux

#175 readded simonGit
  src/app/public/img/simon.jpg
Labels: emotes

#176 Emotes 8
  src/app/emotes.json
  src/app/public/img/DansGame.png
  src/app/public/img/HotPocket.png
  src/app/public/img/aehmok.png
  src/app/public/img/confusedcat.png
  src/app/public/img/pikaWut.png
  src/app/public/img/whutblink.gif
Labels: emotes

#177 added bigF, grossesX and ganzgrossesX, also added :success
  src/app/emotes.json
Labels: emotes

#180 added ArPiiX to codeowners
  CODEOWNERS
Labels: documentation

#179 Refactoring/oop
  src/app/__init__.py
  src/app/commands/__init__.py
  src/app/commands/list.py
  src/app/commands/ping.py
  src/app/emotes/__init__.py
  src/app/emotes/emote_handling.py
  src/app/emotes/emotes.json
  src/app/global_values.py
  src/app/obj/__init__.py
  src/app/obj/command.py
  src/app/obj/message.py
  src/app/obj/system.py
  src/app/obj/system_message.py
  src/app/obj/user.py
  src/app/obj/user_limiter.py
  src/app/obj/user_manager.py
  src/app/public/js/script.js
  src/app/routes.py
  src/app/sockets.py
  src/server.py
  src/utils/__init__.py
  src/utils/shell.py
  tests/test_sockets.py
Labels: breaking, documentation

#181 Update readme.md
  readme.md
Labels: documentation

#182 Zaanposni patch 1
  .github/workflows/basic_check_master.yml
  readme.md
  src/app/sockets.py
Labels: bug, documentation

#186 removed the spellcheck feature from the message box to get rid of the…
  src/app/templates/index.html
Labels: bug, ux

#187 easy displayname change and bug fixes
  src/app/commands/__init__.py
  src/app/commands/list.py
  src/app/commands/ping.py
  src/app/obj/__init__.py
  src/app/obj/system.py
  src/app/obj/system_message.py
  src/app/sockets.py
Labels: breaking, bug, enhancement

#189 Js refactor 1
  src/app/public/js/script.js
  src/app/templates/index.html
Labels: enhancement, ux

#190 removed code Factor badge
  readme.md
Labels: documentation

#192 changed error handling for commands
  src/app/commands/__init__.py
Labels: bug

#197 Version and tabinsert
  src/app/commands/gitversion.py
  src/app/public/js/script.js
Labels: command, enhancement, ux

#200 minor bug fixes
  src/app/obj/message.py
  src/app/obj/user.py
  src/app/sockets.py
Labels: bug, documentation

#204 Toggle autoscroll
  src/app/public/js/script.js
  src/app/templates/index.html
Labels: breaking, enhancement, ux

#209 added first version of example command
  src/app/commands/example.py
Labels: documentation

#210 Gitversion help
  src/app/commands/gitversion.py
Labels: command, enhancement

#213 Emotes and others
  .github/ISSUE_TEMPLATE/feature.md
  src/app/__init__.py
  src/app/emotes/emotes.json
  src/app/public/img/oaHmm.png
  src/app/public/img/pikaWut.png
  src/app/public/img/weSmart.png
  src/app/sockets.py
Labels: enhancement, ux

#216 fix xd
  src/app/commands/gitversion.py
Labels: bug, command

#205 New Command /hangman
  src/app/commands/hangman.py
  src/app/obj/games/hangmangame.py
  src/app/obj/user.py
Labels: command, enhancement

#224 fixed link
  src/app/commands/gitversion.py
Labels: bug, command

#227 fixes #221
  readme.md
Labels: documentation

#231 Create issue_label_bot.yaml
  .github/issue_label_bot.yaml
Labels: documentation, feature, github

#230 fixed error message for offline auth service
  src/app/sockets.py
Labels: bug, ux

#217 game/hangman
  src/app/commands/hangman.py
  src/app/obj/games/hangmangame.py
Labels: command, feature

#232 Implementing embeds (python side)
  requirements.txt
  src/app/obj/command.py
  src/app/obj/embed.py
  src/app/obj/message.py
  src/app/obj/system_message.py
  src/app/obj/user.py
  tests/test_sockets.py
Labels: documentation, feature

#233 making embeds sendable with systemmessenger
  src/app/obj/__init__.py
  src/app/obj/system.py
Labels: bug

#234 added chathistory (pythonside) and api endpoint /api/chathistory
  src/app/__init__.py
  src/app/obj/__init__.py
  src/app/obj/chat_history.py
  src/app/routes.py
  src/app/sockets.py
Labels: feature

#236 added uargh emote
  src/app/emotes/emotes.json
  src/app/public/img/uargh.png
Labels: emotes

#239 added cfg object and minor import refactor
  src/app/__init__.py
  src/app/commands/__init__.py
  src/app/commands/example.py
  src/app/commands/gitversion.py
  src/app/commands/hangman.py
  src/app/commands/list.py
  src/app/commands/ping.py
  src/app/emotes/__init__.py
  src/app/emotes/emote_handling.py
  src/app/obj/chat_history.py
  src/app/obj/user_limiter.py
  src/app/routes.py
  src/app/sockets.py
  src/config-default/main.json
  src/server.py
  src/utils/__init__.py
  src/utils/config.py
Labels: feature

#242 added logininfo to sitebar. displays username and profil pic
  src/app/public/css/general.css
  src/app/public/js/script.js
  src/app/sockets.py
  src/app/templates/index.html
Labels: feature, ux

#243 Image hosting
  .gitignore
  requirements.txt
  src/app/__init__.py
  src/app/public/css/general.css
  src/app/public/js/script.js
  src/app/routes.py
  src/app/templates/index.html
Labels: breaking, feature

#247 Feature/chathistory/js
  src/app/public/js/script.js
  src/config-default/main.json
Labels: feature, ux

#251 added full timestamp on hover
  src/app/public/js/script.js
Labels: ux

#252 added unittest for /api/chathistory
  tests/test_sockets.py
Labels: documentation, tests

#254 refactored unittests
  .github/workflows/unittests.yml
  .github/workflows/unittests_master.yml
  tests/__init__.py
  tests/start.py
  tests/test_objs/__init__.py
  tests/test_objs/sockets.py
  tests/test_sockets.py
  tests/unittests/__init__.py
  tests/unittests/api.py
  tests/unittests/socket_chat.py
  tests/unittests/socket_commands.py
Labels: documentation, tests

#250 Frontend patch 1
  src/app/public/js/script.js
  src/app/templates/index.html
Labels: breaking, bug, feature, ux

#259 Update CODEOWNERS
  CODEOWNERS
Labels: github

#258 changed form input
  src/app/public/js/script.js
Labels: breaking, bug, feature

#260 refactored message object
  src/app/commands/__init__.py
  src/app/obj/embed.py
  src/app/obj/message.py
  src/app/obj/system.py
  src/app/obj/system_message.py
  src/app/public/js/script.js
  src/app/sockets.py
  tests/unittests/socket_chat.py
  tests/unittests/socket_commands.py
Labels: breaking, feature, ux

#263 Zaanposni/refactor
  src/app/__init__.py
  src/app/obj/__init__.py
  src/app/obj/chat_history.py
  src/app/obj/system.py
  src/app/sockets.py
  tests/unittests/api.py
Labels: breaking

#261 new functions for /quote and some minor text output corrections
  src/app/commands/hangman.py
  src/app/commands/quote.py
Labels: command

#264 Update readme.md
  readme.md
Labels: documentation

#268 connection announcement disabled on default with cfg key
  src/app/sockets.py
  src/config-default/main.json
Labels: ux

#269 added STONKS
  src/app/emotes/emotes.json
  src/app/public/img/stonks.png
Labels: emotes

#271 fixed (auto) redirects
  src/app/__init__.py
Labels: ux

#270 added userlist on hover on usercount
  src/app/public/js/script.js
Labels: ux

#273 Feature/commands tab completion
  src/app/public/js/script.js
  src/app/routes.py
  tests/unittests/api.py
Labels: feature, ux

#274 GitHub PR templates
  .github/PULL_REQUEST_TEMPLATE/api_changes.md
  .github/PULL_REQUEST_TEMPLATE/design_changes.md
  .github/PULL_REQUEST_TEMPLATE/documentation.md
  .github/PULL_REQUEST_TEMPLATE/emotes.md
  .github/PULL_REQUEST_TEMPLATE/github_actions.md
Labels: documentation, github

#275 more complex codeowners
  CODEOWNERS
Labels: documentation, github

#276 Feature set
  src/app/public/css/general.css
  src/app/public/js/script.js
  src/app/templates/index.html
Labels: feature, ux

#277 made F a png again and added monkaH and monkaShoot
  src/app/emotes/emotes.json
  src/app/public/img/f.png
  src/app/public/img/monkaH.png
  src/app/public/img/monkaShoot.gif
Labels: emotes, ux

#278 Embed frontend
  src/app/__init__.py
  src/app/commands/__init__.py
  src/app/commands/embedtest.py
  src/app/obj/chat_history.py
  src/app/obj/embed.py
  src/app/public/css/general.css
  src/app/public/js/script.js
Labels: feature, ux

#279 fixed enum
  src/app/obj/message.py
Labels: bug

#280 Embed/commands
  src/app/commands/gitversion.py
  src/app/commands/list.py
  src/app/obj/embed.py
  src/app/obj/system.py
  src/app/public/js/script.js
Labels: breaking, command, ux

#282 Hangman quote embeds
  src/app/commands/hangman.py
  src/app/commands/quote.py
  src/app/templates/index.html
Labels: command, ux

#284 start scripts for debug mode
  src/linux_start.sh
  src/linux_start_disablelogin.sh
  src/linux_start_fulldebug.sh
  src/win_start_fulldebug.bat
  ubuntu_py3.7_patch.sh
  windows_patch.bat
Labels: documentation, feature

#285 stdout changes and cfg optimization
  src/app/__init__.py
  src/app/commands/__init__.py
  src/app/obj/chat_history.py
  src/app/obj/system.py
  src/app/obj/user_limiter.py
  src/app/sockets.py
  src/config-default/main.json
  src/server.py
  src/utils/config.py
Labels: feature

#289 added private chathistory
  src/app/__init__.py
  src/app/obj/__init__.py
  src/app/obj/chat_history.py
  src/app/obj/system.py
  src/app/obj/user_limiter.py
  src/app/obj/user_manager.py
  src/app/public/js/script.js
  src/app/routes.py
  src/app/sockets.py
Labels: feature, ux
