Repository FI18-Trainees/FISocketChat, pull requests merged in 2019-10, with the labels that each got.

#92 added image preview for png, jpg, gif | fixes #49
  src/app/__init__.py
  src/app/public/css/general.css
  src/app/sockets.py
Labels: enhancement, ux

#97 Update emotes.json
  src/app/emotes.json
Labels: enhancement, ux

#104 linux clear console
  .github/workflows/unittest_sockets.yml
  .github/workflows/unittest_sockets_master.yml
  src/app/__init__.py
  src/app/emotes.py
  src/app/shell.py
Labels: bug

#108 Update readme.md
  readme.md
Labels: documentation, enhancement

#116 added message history (arrow up and down) fixes #96
  src/app/public/js/script.js
Labels: enhancement, ux

#129 Emotes 4
  src/app/emotes.json
  src/app/public/img/ayaya.png
  src/app/public/img/pepeJAMJAM.gif
  src/app/public/img/simonW.png
  src/app/public/img/weSmart.gif
  src/app/public/img/weebsout.png
Labels: emotes

#130 Added python 3.6 to the Requirements
  readme.md
Labels: documentation
