Repository FI18-Trainees/FISocketChat, pull requests merged in 2020-01, with the labels that each got.

#330 added POGGERS and sorted "pr0" to a better position
  src/app/emotes/emotes.json
  src/app/public/img/poggers.png
Labels: emotes

#331 Fixed typo
  src/app/templates/index.html
Labels: bug, feature

#335 angular/sidebar now generated by api response
  angular/src/app/sidebar/sidebar.component.html
  angular/src/app/sidebar/sidebar.component.scss
  angular/src/app/sidebar/sidebar.component.ts
  angular/src/interfaces/ISidebarContent.ts
Labels: api, feature

#338 reworked checks on login
  python/src/app/authentication.py
  python/src/app/sockets.py
Labels: bug, ux
